### ISSUE TITLE
Decimals on Payment Gateway

### ISSUE THREAD

**Issue by lingenos** [lillik/magento2-price-decimal#15]
Hello, the module works great, but I have one payment method where I cannot use decimals, but your module doesn't work in this case... the payment method get decimals on the price and taxes

**Comment by lillik** [comment]
Actually this is specific issue. Usually on checkout the price must be with decimals, because you have many factors what can influence the grand total price, like: discount, shipping.
About your payment method, I think that this is issue of payment method, you need to round change  value before send to payment gateway.
